/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itravel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hanadim
 */
public class AdminLogIn extends javax.swing.JFrame {
Connection connect=null;
PreparedStatement statement=null;
ResultSet result=null;
    /**
     * Creates new form AdminLogIn
     */
    public AdminLogIn() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserLable = new javax.swing.JLabel();
        UserNameField1 = new javax.swing.JTextField();
        PasswordLable = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LogInButton = new javax.swing.JButton();
        OwnerHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Log IN");

        jPanel1.setBackground(new java.awt.Color(238, 236, 233));

        UserLable.setText("User Name:");

        UserNameField1.setToolTipText("");
        UserNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameField1ActionPerformed(evt);
            }
        });

        PasswordLable.setText("Password:");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LogInButton.setText("Login");
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserNameField1)
                            .addComponent(PasswordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserLable)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(UserLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        OwnerHeader.setBackground(new java.awt.Color(238, 236, 233));
        OwnerHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/h.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OwnerHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(OwnerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 237, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
     if(UserNameField1.getText().length()!=0&& PasswordField.getText().length()!=0){
        String sql="SELECT * FROM itravel.administrator where User_name=? and Password=?";
            try{
                 connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel","root","Hn@30113011");
                statement=connect.prepareStatement(sql);
                statement.setString(1, UserNameField1.getText());
                statement.setString(2,PasswordField.getText());
                result=statement.executeQuery();
                if(result.next()) {
                    new Admin().setVisible(true);
                        dispose();}
            else{
                JOptionPane.showMessageDialog(null, "Username and Password are not matched please try again "
                 ,"Log in Error",JOptionPane.ERROR_MESSAGE);}

            }catch(SQLException  ex){
                JOptionPane.showMessageDialog(null,ex);
}
     }
        else
        JOptionPane.showMessageDialog(AdminLogIn.this,"You have to fill all the information"
                  ,"Missing Information",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_LogInButtonActionPerformed

    private void UserNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameField1ActionPerformed
         if(UserNameField1.getText().length()!=0&& PasswordField.getText().length()!=0){
        String sql="SELECT * FROM itravel.administrator where User_name=? and Password=?";
            try{
                 connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel","root","Hn@30113011");
                statement=connect.prepareStatement(sql);
                statement.setString(1, UserNameField1.getText());
                statement.setString(2,PasswordField.getText());
                result=statement.executeQuery();
                if(result.next()) {
                    new Admin().setVisible(true);
                        dispose();}
            else{
                JOptionPane.showMessageDialog(null, "Username and Password are not matched please try again "
                 ,"Log in Error",JOptionPane.ERROR_MESSAGE);}

            }catch(SQLException  ex){
                JOptionPane.showMessageDialog(null,ex);
}
     }
        else
        JOptionPane.showMessageDialog(AdminLogIn.this,"You have to fill all the information"
                  ,"Missing Information",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_UserNameField1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
 if(UserNameField1.getText().length()!=0&& PasswordField.getText().length()!=0){
        String sql="SELECT * FROM itravel.administrator where User_name=? and Password=?";
            try{
                 connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/itravel","root","Hn@30113011");
                statement=connect.prepareStatement(sql);
                statement.setString(1, UserNameField1.getText());
                statement.setString(2,PasswordField.getText());
                result=statement.executeQuery();
                if(result.next()) {
                    new Admin().setVisible(true);
                        dispose();}
            else{
                JOptionPane.showMessageDialog(null, "Username and Password are not matched please try again "
                 ,"Log in Error",JOptionPane.ERROR_MESSAGE);}

            }catch(SQLException  ex){
                JOptionPane.showMessageDialog(null,"Somthing went wrong please try again"
                  ,"Error",JOptionPane.WARNING_MESSAGE);
}
     }
        else
        JOptionPane.showMessageDialog(AdminLogIn.this,"You have to fill all the information"
                  ,"Missing Information",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @hanadim  the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JLabel OwnerHeader;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLable;
    private javax.swing.JLabel UserLable;
    private javax.swing.JTextField UserNameField1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
